about/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.AboutView.as_view(), name='about'),
]

blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

homepage/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
]

media/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.AlbumList.as_view(), name='gallery'),
    path('<slug:slug>/', views.AlbumDetail.as_view(), name='album_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from blog import views
from homepage import views

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', include('homepage.urls')),
    path('blog/', include('blog.urls')),
    path('gallery/', include('media.urls')),
    path('about/', include('about.urls')),
    path('portfolio/', include('portfolio.urls'))
]

portfolio/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PortfolioView.as_view(), name='portfolio'),
]

about/models.py
from django.db import models

blog/models.py
from django.db import models
from os.path import join as osjoin
from pictures.models import PictureField


#blog post model
STATUS = (
    (0, "Draft"),
    (1, "Publish")
)

CATEGORY = (
    (0, "Post"),
    (1, "Fiction"),
    (2, "Chords")
)

LANGUAGE = (
    (0, "English"),
    (1, "Czech")
)

class Post(models.Model):
    def art_dir_path(self, filename):
        return osjoin('uploads', str(self.slug), filename)

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    category = models.IntegerField(choices=CATEGORY, default=0)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    language = models.IntegerField(choices=LANGUAGE, default=0)
    art = PictureField(upload_to=art_dir_path, blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

homepage/models.py
from django.db import models

# Create your models here.

media/models.py
from django.db import models
from django.utils import timezone
from django.forms import ModelChoiceField, ModelForm
from os.path import join as osjoin
from pictures.models import PictureField


STATUS = (
    (0, "Draft"),
    (1, "Publish")
)

THUMBNAIL = (
    (0, "No"),
    (1, "Yes")
)

#album model, to collect images into small albums (each album will probably have one video, but let's see about that)
class Album(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=200)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    preview = models.ForeignKey('Picture', related_name='preview' , blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

#this is to only show the pictures that are related to the currently edited album so that thumbnail can only be chosen from those
class AlbumAdminForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['preview'].queryset = Picture.objects.filter(album=self.instance.pk)


#author model, to keep track of the good people whose photos I'm using
class Author(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    website = models.URLField(max_length=200)
    instagram = models.URLField(max_length=200)

    def __str__(self):
        return self.name

#picture model, with better picture field
class Picture(models.Model):
    def album_dir_path(self, filename):
        return osjoin('uploads', str(self.album.slug), filename)

    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)

    picture = PictureField(upload_to=album_dir_path)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render
from django.views import generic

class AboutView(generic.TemplateView):
    template_name = 'about/about.html'

blog/views.py
from django.views import generic

from .models import Post

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/blog_index.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

homepage/views.py
from django.shortcuts import render
from django.views import generic

class HomePageView(generic.TemplateView):
    template_name = 'homepage.html'

media/views.py
from django.views import generic

from .models import Album, Picture

#the list view of all the publushed albums (by status=1)
class AlbumList(generic.ListView):
    queryset = Album.objects.filter(status=1).order_by('-created_on')
    template_name = 'media/album_index.html'

#for viewing all the photos associated with a certain album
class AlbumDetail(generic.DetailView):
    model = Album
    template_name = 'media/album_detail.html'

portfolio/views.py
from django.shortcuts import render
from django.views import generic

class PortfolioView(generic.TemplateView):
    template_name = 'portfolio/portfolio.html'

templates/about/about.html
{% extends 'base.html' %}

{% block links %}
<a class="nav-link fw-bold pb-1 px-0" href="{% url 'blog' %}">Writing</a>
<a class="nav-link fw-bold pb-1 px-0" href="{% url 'gallery' %}">Gallery</a>
<a class="nav-link fw-bold pb-1 px-0" href="{% url 'portfolio' %}">Portfolio</a>
<a class="nav-link fw-bold pb-1 px-0 active" href="{% url 'about' %}">About</a>
{% endblock  %}

{% block content %}
<main class="mb-3 flex-grow-1 mx-3 d-flex flex-column text-center">
    <div class="lead my-auto">
        Something about me and this website coming soon!
    </div>
</main>
{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    {% load django_bootstrap5 %}

    {% bootstrap_css %}

    {% bootstrap_javascript %}

    {% bootstrap_messages %}

    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Gabriel Harangi">
    
    <link href="{% static 'homepage/css/base_styles.css' %}" rel="stylesheet">

    <title>Gabriel Harangi</title>
    <link rel="icon" type="image/x-icon" href="{% static 'homepage/favicon/favicon.ico' %}">

    <!-- For now, adding this block - a few templates have a little bit of their own styles.
    Will move into external stylesheets when finalized -->
    {% block style %}

    {% endblock %}
  </head>

  <body class="d-flex flex-column">
    {% block header %}
      <header class="navbar">
    {% endblock  %}
        <div class="cover-container w-100 mx-auto">
          <nav class="nav nav-masthead float-md-start justify-content-center">
            <a href=" {% url 'home' %} " class="nav-link py-1 px-0 fw-bold fs-5">Gabriel Harangi</a>
          </nav>

          <nav class="nav nav-masthead justify-content-center float-md-end">
            {% block links %}
              <a class="nav-link fw-bold pb-1 px-0" href="{% url 'blog' %}">Writing</a>
              <a class="nav-link fw-bold pb-1 px-0" href="{% url 'gallery' %}">Gallery</a>
              <a class="nav-link fw-bold pb-1 px-0" href="{% url 'portfolio' %}">Portfolio</a>
              <a class="nav-link fw-bold pb-1 px-0" href="{% url 'about' %}">About</a>
            {% endblock  %}
          </nav>
        </div>
      </header>

    
    
    <!-- Main content here -->
    {% block content %}
      
    {% endblock  %}
      
    

      <footer>
        <div class="cover-container mx-auto mt-5 text-black-50 text-center">
          <p>Backend by <a href="https://djangoproject.com/" class="link-dark">Django</a>, frontend by <a href="https://getbootstrap.com/" class="link-dark">Bootstrap</a>.</p>
        </div>
      </footer>

  </body>

</html>

templates/base_bu.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        {% load django_bootstrap5 %}

        {% bootstrap_css %}

        {% bootstrap_javascript %}

        {% bootstrap_messages %}
    
        <title>Gabriel Harangi</title>
         

    </head>

    <body class="bg-light">

      <!-- Navigation -->
          <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light bg-gradient">
              <div class="container">
                  <a class="navbar-brand p-2" href="{% url 'home' %}">Gabriel Harangi</a>
                  <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                      aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarResponsive">
                      <ul class="nav navbar-nav ms-auto">
                        <li class="nav-item">
                          <a class="nav-link" href="#">Portfolio</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'blog' %}">Blog</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Gallery</a>
                        </li>
                      </ul>
                    </div>
              </div>
          </nav>

          <main class="container">
            <div class="row">

              <!-- left sidebar here, to disappear when we go below large -->
              <div class="col-lg-2 d-none d-lg-block">
              </div>

              <!-- main content here in a middle column -->
              <div class="col-lg-8 col-md-12">
                {% block content %}

                {% endblock content %}
              </div>
              <!-- right sidebar, to disappear when we go below large -->
              <div class="col-lg-2 d-none d-lg-block">
              </div>
            </div>
          </main>
    </body>
</html>

templates/blog/blog_base.html
{% extends 'base.html' %}

{% block links %}
<a class="nav-link fw-bold pb-1 px-0 active" href="{% url 'blog' %}">Writing</a>
<a class="nav-link fw-bold pb-1 px-0" href="{% url 'gallery' %}">Gallery</a>
<a class="nav-link fw-bold pb-1 px-0" href="{% url 'portfolio' %}">Portfolio</a>
<a class="nav-link fw-bold pb-1 px-0" href="{% url 'about' %}">About</a>
{% endblock %}

templates/blog/blog_index.html
{% extends "blog/blog_base.html" %}

{% load pictures %}


{% block content %}
  <main class="mb-3 mx-3 d-flex justify-content-center">
      <div class="cover-container">

        <div class="jumbotron jumbotron-fluid">
            <div class="container p-3 p-md-4 p-lg-5 my-4">
              <h1 class="display-4">My stories.</h1>
              <p class="lead">Some are in English, some in Czech. All of them are fictional. The artwork was AI generated at <a href="https://nightcafe.studio/" class="link-dark">NightCafé</a>,
                which evokes a slightly odd, undefined atmosphere, much like the magical realism of the stories themselves.</p>
            </div>
          </div>

        <div class="row g-2">
            {% for post in post_list %}
                <div class="col-sm-6">
                    <div class="card">
                        <img src="{% img_url post.art file_type="webp" width=2200 %}" class="img-fluid card-img-top" alt="{{ post.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text">{{ post.content|safe|slice:":180" }}...</p>
                            
                            <div class="d-flex justify-content-end">
                                <a href="{% url 'post_detail' post.slug %}" class="btn btn-outline-dark stretched-link">...continue reading</a>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
      </div>
    </main>
{% endblock %}

templates/blog/post_detail.html
{% extends "blog/blog_base.html" %}

{% load pictures %}

{% block content %}
<main class="my-3 mx-3">
    <div class="cover-container m-auto">
        {% if post.art %}
        <div class="mb-3">
            <img src="{% img_url post.art file_type="webp" width=2200 %}" class="img-fluid" alt="{{ post.title }}">
        </div>
        {% endif %}
        <h1>{{ post.title }}</h1>
        {{ post.content | safe}}
    </div>
    <div class="container text-center mt-5">
        <a href="#top" class="btn btn-outline-dark">Back to top</a>
    </div>    
</main>
{% endblock %}

templates/homepage.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    {% load django_bootstrap5 %}

    {% bootstrap_css %}

    {% bootstrap_javascript %}

    {% bootstrap_messages %}

    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Gabriel Harangi">
    
    <link href="{% static 'homepage/css/homepage_styles.css' %}" rel="stylesheet">

    <title>Gabriel Harangi</title>
    <link rel="icon" type="image/x-icon" href="{% static 'homepage/favicon/favicon.ico' %}">

  <style>
    body {
      background: url('{% static 'homepage/imgs/IMA_bw.jpg' %}') no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      background-size: cover;
      -o-background-size: cover;
      box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);
    }
  </style>

</head>

<body class="d-flex flex-column text-bg-dark">
    <header class="navbar">
      <div class="cover-container w-100 mx-auto">
        <nav class="nav nav-masthead float-md-start justify-content-center">
          <a href=" {% url 'home' %} " class="nav-link py-1 px-0 fw-bold fs-5">Gabriel Harangi</a>
        </nav>

        <nav class="nav nav-masthead justify-content-center float-md-end">
            <a class="nav-link fw-bold pb-1 px-0" href="{% url 'blog' %}">Writing</a>
            <a class="nav-link fw-bold pb-1 px-0" href="{% url 'gallery' %}">Gallery</a>
            <a class="nav-link fw-bold pb-1 px-0" href="{% url 'portfolio' %}">Portfolio</a>
            <a class="nav-link fw-bold pb-1 px-0" href="{% url 'about' %}">About</a>
        </nav>
      </div>
    </header>

  <main class="px-3 my-auto text-center">
    <div class="cover-container w-100 m-auto">
      <div class="p-2">
        <h1 class="display-4">Welcome to my site.</h1>
          <p class="lead">It is a place for me to store some memories and creations, both artistic and professional. And for you, if you wish, to get to know me a little.</p>
          <p class="lead">
            <a href="{% url 'blog' %}" class="btn btn-lg btn-outline-light fw-bold">Writing</a>
            <a href="{% url 'gallery' %}" class="btn btn-lg btn-outline-light fw-bold">Gallery</a>
            <a href="{% url 'about' %}" class="btn btn-lg btn-outline-light fw-bold">Portfolio</a>
          </p>
          <p class="lead">(Work in progress.)</p>
      </div>
    </div>
  </main>

</body>

</html>

templates/homepage_old.html
{% extends "base.html" %}

{% load static %}

{% block content %} 

<!-- Portfolio card. Disappears below medium. -->
<div class="card mb-3 d-none d-md-block">
    <div class="row g-0">
      <div class="col-md-8">
        <img src="{% static 'homepage/imgs/ima_preview_1.jpg'  %}" class="img-fluid card-img-start" alt="IMA image">
      </div>
      <div class="col-md-4">
        <div class="card-body">
          <h5 class="card-title">Portfolio</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Pretty cool, huh?</small></p>
        </div>
      </div>
    </div>
</div>

<!-- Replaces large (and bigger) portfolio card when on medium or lower -->
<div class="card mb-3 d-block d-md-none">
  <img src="{% static 'homepage/imgs/ima_preview_1.jpg'  %}" class="card-img-top" alt="IMA image">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
  </div>
</div>

<!-- Writing (blog) preview card -->
<div class="card mb-3">
    <div class="row flex-row-reverse g-0">
      <div class="col-md-8">
        <img src="{% static 'homepage/imgs/writing01.jpg'  %}" class="img-fluid" alt="Writing">
      </div>
      <div class="col-md-4">
        <div class="card-body">
          <h5 class="card-title">Writing</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <a href="{% url 'blog' %}" class="btn btn-light stretched-link">Go somewhere</a>
        </div>
      </div>
    </div>
</div>

<!-- Gallery preview card -->
<div class="card mb-3 d-none d-md-block">
    <div class="row g-0">
      <div class="col-md-8">
        <img src="{% static 'homepage/imgs/pk_gerlev_kong.jpg'  %}" class="img-fluid" alt="Gallery">
      </div>
      <div class="col-md-4">
        <div class="card-body">
          <h5 class="card-title">Gallery</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Pics and vids for the peeps!</small></p>
        </div>
      </div>
    </div>
</div>

<div class="card mb-3 d-block d-md-none">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
  </div>
  <img src="{% static 'homepage/imgs/pk_gerlev_kong.jpg'  %}" class="card-img-bottom" alt="Gallery">
</div>



{% endblock %}

templates/media/album_detail.html
{% extends 'media/media_base.html' %}

{% load pictures %}

{% block style %}
<style>
  .masonry { 
    display: flex;
    flex-flow: row wrap;
    width: 100%;
  }
  
  @media screen {
    .masonry-brick {
      flex: auto;
      height: 400px;
      min-width: 150px;
    }
  }

  @media screen and (max-width: 992px) {
    .masonry-brick {
      flex: auto;
      height: 350px;
      min-width: 150px;
    }
  }

  @media screen and (max-width: 768px) {
    .masonry-brick {
      flex: auto;
      height: 250px;
      min-width: 150px;
    }
  }


  .masonry-img {
    object-fit: cover;
    width: 100%;
    height: 100%;
  }

  .masonry-brick:nth-child(4n+1) {
    width: 250px;
  }
  .masonry-brick:nth-child(4n+1):nth-child(4n+2) {
    width: 325px;
  }
  .masonry-brick:nth-child(4n+1):nth-child(4n+3) {
    width: 180px;
  }
  .masonry-brick:nth-child(4n+1):nth-child(4n+4) {
    width: 380px;
  } 

</style>

{% endblock  %}

{% block content %}
    <main class="mb-5 flex-grow-1">
      <div class="container-xl">
        <div class="masonry">
          {% for picture in album.picture_set.all %}
            <div class="masonry-brick">
              <img src="{% img_url picture.picture file_type="webp" width=1000 %}" class="masonry-img" alt="{{ picture.title }}">
            </div>
          {% endfor %}
        </div>
      </div>
    </main>
{% endblock  %}

templates/media/album_detail_bu.html
<!--
  This one is a bit wonky. It has a working carousel, but portrait images don't render the way I would like them to.
-->


{% extends 'media/media_base.html' %}

{% load pictures %}

{% block content %}
    <main class="mb-5" style="height: 100vh">
        <a name="top"></a>
        <div class="container text-center h-100">
            
            <div id="myCarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                {% for picture in album.picture_set.all %}
                 {% if picture == album.preview %}
                  <div class="carousel-item active">
                    <img src="{% img_url picture.picture file_type="webp" width=2200 %}" class="img-fluid" alt="{{ picture.title }}">
                    {{ picture.title }} by <a href="{{ picture.author.website }}">{{ picture.author }}</a>
                  </div>
                  {% else %}
                  <div class="carousel-item">
                    <img src="{% img_url picture.picture file_type="webp" width=2200 %}" class="img-fluid" alt="{{ picture.title }}">
                    {{ picture.title }} by <a href="{{ picture.author.website }}">{{ picture.author }}</a>
                  </div>
                  {% endif %}
                {% endfor %}
                
                <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>


            
        </div>
    </main>
{% endblock  %}

{% block script %}
<script>
    const myCarouselElement = document.querySelector('#myCarousel')
    const carousel = new bootstrap.Carousel(myCarouselElement, {
      interval: 2000,
      wrap: true
    })
</script>
{% endblock  %}

templates/media/album_index.html
{% extends 'media/media_base.html' %}

{% load pictures %}

{% load static %}

{% block style %}
    <link href="{% static 'media/css/album_index_styles.css' %}" rel="stylesheet">
{% endblock  %}

{% block content %}
    <main class="mb-3 mx-3 flex-grow-1 d-flex flex-column align-items-center">

        <div class="cover-container">
            <div class="jumbotron jumbotron-fluid">
                <div class="container p-3 p-md-4 p-lg-5 my-4">
                  <h1 class="display-4">Photography.</h1>
                  <p class="lead">
                    Mostly my own. There are a few pictures, however, taken by others. All carry good memories.
                  </p>
                </div>
              </div>
        </div>


        <div class="container p-0">
            <div class="row g-1">
                {% for album in album_list %}
                    <div class="col-sm-6 col-lg-4">
                        <a href="{% url 'album_detail' album.slug %}">
                            <div class="img-box">
                            
                                <img src="{% img_url album.preview.picture file_type="webp" width=600 %}" class="image" alt="placeholder">
                            
                                <div class="overlay">
                                    <div class="overlay-text">
                                        <h5>
                                            {{ album.title | upper }}
                                        </h5>
                                        <p class="fs-6">
                                            {{ album.description }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}       
            </div>
        </div>
    </main>
{% endblock  %}

templates/media/media_base.html
{% extends 'base.html' %}

{% block links %}
    <a class="nav-link fw-bold pb-1 px-0" href="{% url 'blog' %}">Writing</a>
    <a class="nav-link fw-bold pb-1 px-0 active" href="{% url 'gallery' %}">Gallery</a>
    <a class="nav-link fw-bold pb-1 px-0" href="{% url 'portfolio' %}">Portfolio</a>
    <a class="nav-link fw-bold pb-1 px-0" href="{% url 'about' %}">About</a>
{% endblock  %}

templates/portfolio/portfolio.html
{% extends 'base.html' %}

{% load static %}

{% block links %}
    <a class="nav-link fw-bold pb-1 px-0" href="{% url 'blog' %}">Writing</a>
    <a class="nav-link fw-bold pb-1 px-0" href="{% url 'gallery' %}">Gallery</a>
    <a class="nav-link fw-bold pb-1 px-0 active" href="{% url 'portfolio' %}">Portfolio</a>
    <a class="nav-link fw-bold pb-1 px-0" href="{% url 'about' %}">About</a>
{% endblock  %}

{% block content %}
<main class="mb-3 flex-grow-1 mx-3 d-flex flex-column align-items-center">
    
    <div class="cover-container">
    
        <div class="card text-white">
            <img src="{% static 'homepage/imgs/ima_preview_1.jpg' %}" class="card-img" alt="IMA1">
            <div class="card-img-overlay">
                <h5 class="card-title">In Motion Academy</h5>
                <p class="card-text">
                    Yeah I built a nice gym! And this is just some filler text to see how it will look in action. I can't say I like it very much, yet.
                </p>
            </div>
        </div>

        <div class="card mb-3">
            <div class="row g-0">
              <div class="col-md-7">
                <img src="{% static 'homepage/imgs/ima_preview_1.jpg' %}" class="img-fluid" alt="IMAcademy">
              </div>
              <div class="col-md-5">
                <div class="card-body">
                  <h5 class="card-title">In Motion Academy</h5>
                  <p class="card-text">Who knows, maybe this will look much nicer. I guess it might, as I don't really plan to crop the images. Hmm. Hmm indeed.</p>
                </div>
              </div>
            </div>
          </div>
    
    </div>

</main>
{% endblock  %}